### ISSUE TITLE
Calendar: Side calendar

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/hbsc#10]
- [x] I believe we're imagining the calendar in the left panel to be sticky on scroll. Also the month should change when we reach the next month through scrolling.

- [x] Events which are assigned the same month need to be attached to one another. The break is for different months only.

- [x] Can the arrows for next and previous months rollover to red same with the dates (but not like the current date treatment).

- [x] Can the month type in the mini-cal have the same treatment as the month in the event module? At the moment it looks bolder.

**Comment by spalepin** [comment]
This is done!

Thanks
Simon
