### ISSUE TITLE
Stowe Prize: Years

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#103]
The client would like it if the years that the Stowe Prize winners won (both student and literary) were displayed on the landing pages, perhaps within the "Winner" banner (e.g. 2017 Winner). How much time might it require for this to be automatically displayed? There is a section in WordPress where they check off the year for each winner. 
<img width="1091" alt="screen shot 2018-01-11 at 2 41 36 pm" src="https://user-images.githubusercontent.com/1680051/34843850-afa0dd78-f6dd-11e7-8c01-bc38b45f777e.png">

**Comment by A-Tawfik** [comment]
<img width="1188" alt="screen shot 2018-01-30 at 1 05 03 pm" src="https://user-images.githubusercontent.com/17328969/35582920-42076b84-05be-11e8-8472-fe332a668bd1.png">

are we feeling good about this look?

it will only post the "first added" year. if they have more then one year the rest will be ignored on this banner

**Comment by Jessdwilson** [comment]
this works for me, thanks!
