### ISSUE TITLE
Why Visit Stowe Center user comments

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#11]
The client would like visitors to be able to leave comments on this page beneath "If you can't visit in person". When I checked the Discussion > Allow Comments box it appears first on the page

**Comment by spalepin** [comment]
Hello,

The comments can now be activated for the regular pages. 
Unless we create a new "module", it's not possible to choose the position of the comments tread.
It will appear at the very bottom of the page.

Thanks
Simon
