### ISSUE TITLE
Stowe Center Impact & Issues content question

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#12]
The content from the client varies from what is currently on the site, will we be able to edit the tabs and info under statistics? If not, we will confirm with the client what these should state.

**Comment by spalepin** [comment]
Hello,

Sure, it is possible to modify the content. The statistics, texts, graphics are all editable and will be updated automatically.

Please don't hesitate if you have any questions.
Simon

**Comment by Jessdwilson** [comment]
It seems some of the info on this page is hard-coded, could it be possible for us to edit the map that appears in the header?

For the **2016** Stowe Prize Winners, can this appear closer to the mockup? Right now just the names appear
<img width="591" alt="screen shot 2017-07-17 at 6 57 16 pm" src="https://user-images.githubusercontent.com/1680051/28293427-1aacf28e-6b22-11e7-920b-10bacedea0ea.png">

**Comment by spalepin** [comment]
Hello,

The map gps coordinates aren't editable. I embedded a mapbox and I also added a red pin (center point Hartford.

For the winners, the picture thumbnail can be cropped & resized in the admin. I added a plugin that allows you to do that very easily. I replaced the image of Martese, I had a cropped version.

Thanks
Simon

**Comment by Jessdwilson** [comment]
For Stowe Center Impact & Issues, the map that was in the header is now missing. 

Where would we edit the 2017 Stowe Prize Winners on this page? Or should this info automatically appear? 

<img width="1133" alt="impact issues map" src="https://user-images.githubusercontent.com/1680051/28529667-26f58c76-705f-11e7-8f1d-285850219adb.png">
<img width="1138" alt="impact issues winners" src="https://user-images.githubusercontent.com/1680051/28529681-2d443aa0-705f-11e7-98da-6635a814c336.png">

**Comment by spalepin** [comment]
Hello,
I added the stowe prize module to the page and I removed the hardcoded winners.
I put back the map, 1 file was missing for the theme export.

Please let me know if you have any questions!
Simon
