### ISSUE TITLE
adding a numbered list

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#13]
I'm trying to add a numbered list to the [Membership](http://site27.webitinteractive.ca/membership/) page but it appears as bullets on the front end

<img width="771" alt="screen shot 2017-06-30 at 3 40 58 pm" src="https://user-images.githubusercontent.com/1680051/27751484-901406f0-5daa-11e7-9f1e-0d7e0d4efa67.png">

**Comment by spalepin** [comment]
This is fixed.

Thanks!
Simon
