### ISSUE TITLE
Main Navigation

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/hbsc#16]
- [x] On the mid-page expanded. I think we need to visualize which page the user is currently on. The collapsed state is clear what page it is however, on expanded it's unclear. Everything is hidden again. Is there a way to have the children page level open and the current page highlighted red?

- [x] Slow down the reappearance of the full logo when users scroll to the top of the page. It could be closer to how it disappears.

- [x] Is there a way to make the expanded and collapsed view interaction less rigid and have a smoother transition? I'm imagining something like these examples: https://uimovement.com/ui/3470/travel-app-filtering/
https://uimovement.com/ui/2839/rise-blocks-authoring/

- [x] Question: How easy is it to re-order the nav items? I'm thinking about making the current page the top nav item depending on the page users are on. 

- [x] When the navigation is in it's collapsed state. Clicking on the parent type (about, visit, support, etc...) that should automatically open the list without showing all the items in the menu. Makes it easier to move between the children pages.

**Comment by ryanobsub** [comment]
When expanding a main category on the nav, close all already open categories. Only one category expanded at a time. 
<img width="2227" alt="screen shot 2017-06-30 at 4 48 11 pm" src="https://user-images.githubusercontent.com/29466783/27753519-fb7743a4-5db3-11e7-9d65-67491693d2af.png">

**Comment by ryanschoenherr** [comment]
When expanding a main category on the nav, close all already open categories. Only one category expanded at a time.
<img width="2227" alt="screen shot 2017-06-30 at 4 48 11 pm" src="https://user-images.githubusercontent.com/29466783/27753561-26bd99aa-5db4-11e7-865e-a00eb64bda59.png">

**Comment by ryanschoenherr** [comment]
Click off navigation to close nav in addition to the collapse arrow.

**Comment by ryanschoenherr** [comment]
- [x] On homepage - collapse arrow should disappear when nav is extended at the top.
- [x] On homepage - nav should always be extended on top of homepage, collapses when scroll away.

- [x] Nav shouldn't be as wide, too close to the intro text at top.

**Comment by spalepin** [comment]
Done!

**Comment by Jessdwilson** [comment]
the navigation should auto collapse when a user scrolls down any page on the site but the navigation is remaining open, I noticed this in Chrome, Safari and Firefox

**Comment by kpettinga** [comment]
@Jessdwilson on what pages is this happening for you? It seems to work well for me so far.

**Comment by Jessdwilson** [comment]
if the menu is expanded on a page by clicking the carrot on the bottom right then a user scrolls down the page, away from the menu, it should collapse. I notice this on all pages (screenshot example attached)

<img width="1174" alt="screen shot 2017-08-31 at 7 32 05 am" src="https://user-images.githubusercontent.com/1680051/29921119-815eaac6-8e1e-11e7-9d74-ab8b975847fe.png">

**Comment by kpettinga** [comment]
Should be all set.
