### ISSUE TITLE
Salons at Stowe: Card title

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/hbsc#17]
- [x] H2 should be 0 letter-spacing not 0.2. 

![image](https://user-images.githubusercontent.com/12611145/27753443-9c4afe7a-5db3-11e7-8714-2610f2f72a00.png)

- [x] Do we have the option to use the condensed slab serif here?

**Comment by spalepin** [comment]
Hello,

When editing an event, you can use the subtitle field to display part of the title as condensed serif. 

![image](https://user-images.githubusercontent.com/1513192/27866713-5ff1671a-6165-11e7-9f02-e3f90b895eb9.png)

http://site27.webitinteractive.ca/events/in-limbo-challenges-facing-undocumented-students/

Please let me know if that makes sense to you.

Thanks
Simon
