### ISSUE TITLE
Homepage Card Orientation

### ISSUE THREAD

**Issue by ryanschoenherr** [ObjectiveSubject/hbsc#19]
Card's should be vertically oriented (portrait) - closer to the mock up. Larger type, narrow type field.
<img width="696" alt="screen shot 2017-06-30 at 5 13 18 pm" src="https://user-images.githubusercontent.com/29466783/27754240-89206bce-5db7-11e7-96b5-010f26301b35.png">
.

**Comment by spalepin** [comment]
This is done!
Thanks

**Comment by elliotarthur** [comment]
Hey @spalepin, can news tag should be white instead of black?

![image](https://user-images.githubusercontent.com/12611145/28027647-c9bf5aac-6567-11e7-87fa-256091556d9e.png)

**Comment by spalepin** [comment]
Hello,

It renders white on my site. Please let me know if it works on your side.

Thanks!
Simon
