### ISSUE TITLE
Maps

### ISSUE THREAD

**Issue by ryanschoenherr** [ObjectiveSubject/hbsc#20]
replace all static maps with custom mapbox map
https://api.mapbox.com/styles/v1/objectivesubject/cj3nb9qzp000m2smqxu8q0l3p.html?title=true&access_token=pk.eyJ1Ijoib2JqZWN0aXZlc3ViamVjdCIsImEiOiJPY25wYWRjIn0.AFZPHessR_DGefRkzPilDA#6.7/39.800877/-75.011684/0

**Comment by Jessdwilson** [comment]
can we have the option to include a map under Directions on Visit > The Stowe Center

**Comment by spalepin** [comment]
Done!

**Comment by elliotarthur** [comment]
The moving functionality is disabled on the map and shouldn't we include a pin on where the center is?! @ryanschoenherr

**Comment by spalepin** [comment]
I removed the moving/zooming functionality. It makes it harder to navigate the page and you may zoom in accidentally. It's not a problem to add a pin. I will close the issue once it's done.

Thanks!

**Comment by ryanschoenherr** [comment]
@spalepin Here's the pin SVG
[HBSC_Pin.svg.zip](https://github.com/ObjectiveSubject/hbsc/files/1166173/HBSC_Pin.svg.zip)
