### ISSUE TITLE
Mobile and Safari footer

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#28]
when viewed on an iphone 6 and in Safari version 10.1 the nav items in the footer aren't aligned, can this be fixed so they all align? 

![iphone 6 footer](https://user-images.githubusercontent.com/1680051/28281111-046b7dfc-6af4-11e7-9d11-91bebb173198.PNG)
<img width="1316" alt="safari 10 1 footer" src="https://user-images.githubusercontent.com/1680051/28281124-0d0c571a-6af4-11e7-849f-1dd17d280386.png">

**Comment by spalepin** [comment]
fixed
