### ISSUE TITLE
Add navigation items to footer

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#3]
Per the mockup:
<img width="810" alt="screen shot 2017-06-28 at 5 24 26 pm" src="https://user-images.githubusercontent.com/1680051/27661026-ac20d8f8-5c26-11e7-82ad-9e028172a1e9.png">

**Comment by spalepin** [comment]
Hello,

I can display the primary sections in the footer but none of them are associated with a page. Would you like to link them to the first page of each section?
e.g. VISIT ->  http://site27.webitinteractive.ca/the-stowe-center/

Thanks
Simon

![image](https://user-images.githubusercontent.com/1513192/27700610-1eeff10c-5ccc-11e7-9e0f-efd46dbd80c0.png)

**Comment by Jessdwilson** [comment]
Yes, that makes sense. Thanks!

**Comment by spalepin** [comment]
Hello,

Usually, I would make a different menu for the footer that you can manage independently. The only problem is that you would have to change the footer links manually each time you modify the header menu.

Instead, I generated the footer menu items dynamically based on the header menu. It takes the 1st level menu name and the url of the first child item(2nd level).

Please let me know if that works for you!
Thanks
Simon

**Comment by Jessdwilson** [comment]
That works, thanks!
