### ISSUE TITLE
Homepage HBS content

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#30]
where in WordPress would we edit this content/Learn More button? I didn't see it on the homepage page, it should link to HBS Life 

<img width="762" alt="screen shot 2017-07-17 at 2 29 39 pm" src="https://user-images.githubusercontent.com/1680051/28283810-f3dc3cf2-6afc-11e7-9692-e029f827b8f2.png">

**Comment by spalepin** [comment]
I added a new section in the admin. You can modify/add/delete the content, links and button.

Thanks!
Simon
