### ISSUE TITLE
questions posts news & announcements

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#31]
I thought content added under Posts would appear on the News & Announcements page, but when I added content to a Post it doesn't show up on the site. Can you confirm where content added to posts appear on the site, if anywhere? 

For News & Announcements, would we need to add all content to the individual News & Announcements page?

**Comment by spalepin** [comment]
Hello,

The pages are done!

**Posts list**
https://hbstowecenter.wpengine.com/about/news-announcements/

**Post**
https://hbstowecenter.wpengine.com/about/news-announcements/bank-of-america-selects-the-stowe-center-for-art-conservation-project-grant/

**Comment by Jessdwilson** [comment]
Thanks! I added a couple additional posts and noticed there's quite a bit of spacing between each post on the News & Announcements page, is it possible to reduce the spacing a bit?

<img width="1218" alt="screen shot 2017-07-31 at 3 54 24 pm" src="https://user-images.githubusercontent.com/1680051/28795685-c826ea6e-7608-11e7-8242-73c8fc697ef9.png">

**Comment by spalepin** [comment]
Hello,

The spacing between the posts is caused by the missing images. I revised the layout to prevent the spacing issue.

Thanks!
Simon
