### ISSUE TITLE
WPEngine plugin disallowed

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#34]
we received the below notification from wpengine, can you resolve?

As part of the normal security and performance scans that WP Engine runs on our customer sites, we also scan for plugins that may be on our disallowed plugin list, and adversely affecting site performance and / or security.

We just scanned your WordPress installation 'hbstowecenter' and discovered [hello.php], which is/are on our disallowed list and will result in sub-optimal performance for your site.

Our policy about plugins we don't allow is here: http://support.wpengine.com/disallowed-plugins/.

We're sending you this email to request that you remove [hello.php] from your site within the next 7 days. In 7 days, we'll automatically remove those plugins from your site, and we want to give you plenty of time to find and test suitable replacements.  For many plugins, we have suggested replacements.

If you have any questions, please let us know in a support ticket http://wpengine.zendesk.com

**Comment by spalepin** [comment]
Thank you for the information. The file has been removed.
Thanks!
Simon
