### ISSUE TITLE
The Stowe Center hours sidebar content

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#35]
I see that the hours are hard-coded, we will want to display sidebar content next to the hours as in the attached. This information should be editable in wordpress 
<img width="1119" alt="screen shot 2017-07-18 at 11 39 03 am" src="https://user-images.githubusercontent.com/1680051/28326089-c67dd2aa-6bad-11e7-8def-feb1dea71f4d.png">

**Comment by spalepin** [comment]
Hello,

The sidebar content is already editable. Please see attached screenshot. Don't hesitate to get back to me if you have any question.

**Comment by Jessdwilson** [comment]
I see that I can edit the sidebar content, but the sidebar content with the closed times and holiday hours needs to appear next to the **Hours** in the first module, I see that the Hours are hard-coded. Possible to have the sidebar content appear next to the hours and remain editable?

<img width="1030" alt="screen shot 2017-07-24 at 10 43 33 am" src="https://user-images.githubusercontent.com/1680051/28529122-b6b6fe0a-705d-11e7-9006-f179301355e9.png">

**Comment by joauv** [comment]
All the data that needs to be accessed site-wide (contact info, social media, opening hours) is in the "General Settings" on the left.

![image](https://user-images.githubusercontent.com/7191186/28538203-6b0d6700-707b-11e7-8cf7-e9de81c07418.png)

Changing the opening hours for any day on that page will automatically update the table in "[The Stowe Center](http://hbstowecenter.wpengine.com/visit/the-stowe-center/)". You can also force close for a day (i.e. on a holiday), and it would automatically replace the "Open Today: X to Y" with "Closed Today" on the page and in the site header.

From January to March, they'd simply have to leave the "Tuesday" field empty, and it would display as "Closed".
