### ISSUE TITLE
Header button links

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#36]
on all pages with module links in the header, the links connect to the homepage and not the content within the page 
<img width="1095" alt="screen shot 2017-07-18 at 12 32 24 pm" src="https://user-images.githubusercontent.com/1680051/28328702-5d5c1bd0-6bb5-11e7-86fd-3cdb3ccfe471.png">

**Comment by spalepin** [comment]
Fixed!
