### ISSUE TITLE
staff & board bullets and order

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#39]
- [x] there shouldn't be bullets on the staff & board page, can these be removed?
- [x] Also, the client will want to have control over the order of staff and board as they appear on the site. Can we add an order option?
<img width="892" alt="screen shot 2017-07-18 at 2 18 02 pm" src="https://user-images.githubusercontent.com/1680051/28332950-704b9248-6bc4-11e7-9d7b-3c2db3c276ae.png">

**Comment by spalepin** [comment]
Fixed

**Comment by Jessdwilson** [comment]
Thanks!  The client will want to have control over the order of staff and board as they appear on the site. Can we add an order option?

**Comment by spalepin** [comment]
Hello,

Since we are using many custom types + modules, we have to make sure it doesn't break anything else. It might take about 1 h of work to confirm if that works properly with the existing structure.

Please let me know if you want to go ahead with the reorder option.
Simon

**Comment by Jessdwilson** [comment]
Ok, yes I know it will be a priority for the client to be able to reorder staff & board, so please go ahead. Thanks!

**Comment by joauv** [comment]
Staff/Board reordering is now possible via the 'People/Re-Order' menu-item on the left in the WP Admin. All posts are displayed in a single list, but will be automatically arranged by category (Board, Salon Hosts, Staff in that order) on the 'Staff & Board' page, following the order specified. Simply drag-and-drop items to re-arrange them, and click 'Update' (at the bottom) when done.
