### ISSUE TITLE
Spacing of elements Calendar in Chrome

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#4]
The spacing of elements on the Calendar page when viewed in Chrome are too tight, but look accurate when viewed in Firefox and Safari. Viewing this in Chrome Version 58.0.3029.110
<img width="1308" alt="screen shot 2017-06-28 at 5 29 31 pm" src="https://user-images.githubusercontent.com/1680051/27661180-61a8cbea-5c27-11e7-8cc0-01dcca0864a8.png">

**Comment by spalepin** [comment]
Hello,
I verified on chrome, safari and firefox on pc and mac. On my side, I see the same spacing. However, if you resize your window the spacing between the elements will  be smaller.

Please see attached screen shots and let me know if it behaves the same way on your side.

Thank you!
Simon

![calendar_chrome_small_window](https://user-images.githubusercontent.com/1513192/27694279-aa1c5832-5cb9-11e7-99c5-407154e6ed3a.jpg)
![calendar_chrome_fullwidth](https://user-images.githubusercontent.com/1513192/27694280-aa23aad8-5cb9-11e7-8b54-feb858719539.jpg)
