### ISSUE TITLE
Collections page links and carousels

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#40]
- [x] On the Collections page we don't necessarily need each module to include a title, but for those that do include titles they should appear as links in the header. If a module does not include a title can we avoid having the empty box in the header as in the attached? 
<img width="1030" alt="collection module title" src="https://user-images.githubusercontent.com/1680051/28342854-6474d096-6be8-11e7-88ae-8e3d1a852049.png">

- [x] We would like to use the media collection/carousel for the Collections, but there are constraints for the image sizes, can this be adjusted to autofit the image so it isn't cutoff? 

- [x] Can it be optional to include slide copy? In mobile or tablet the slide copy overlaps the image. Ideally, we would have the option to include copy or badge text

- [x] I tested adding a slide button link but when viewed on the site the link doesn't appear to be active

- [x] I unchecked "module button" in WordPress but the "View Collection" button persists in the HBS collection carousel 

<img width="650" alt="screen shot 2017-07-18 at 6 46 38 pm" src="https://user-images.githubusercontent.com/1680051/28343106-a4a520a2-6be9-11e7-9ce9-57b7a61dfc43.png">

**Comment by Jessdwilson** [comment]
this will be a lower priority item, we are thinking a lightbox would be a better solution for this

**Comment by Jessdwilson** [comment]
The above issues are still relevant, but for the Collections page we think a better solution would be to implement a lightbox. See attached mockup for what we're thinking, the "Load More" button would show all rows of images. When clicking on an image the lightbox appears with text below the image with more info. 
[HBSC Web Design Refinement  collection lightbox 20170721 RS.pdf](https://github.com/ObjectiveSubject/hbsc/files/1166459/HBSC.Web.Design.Refinement.collection.lightbox.20170721.RS.pdf)

**Comment by spalepin** [comment]
Hello,

I'm sorry for the delay. I will evaluate how much time this would take to implement. 
I will get back to you shortly for the Collections.

Thanks
Simon

**Comment by spalepin** [comment]
Hello,

**Images crop**: The images are resized automatically to fit inside its container. 
The size and the aspect ratio of the image are respected.
As you resize the window, the image container width will be smaller and the image remains the same size.

I suggest that you use the image cropping tool plugin (already installed) if you need to crop/adjust an image.

**Badge**: The badge wasn't supposed to be used in this carousel, I forgot to remove it. It might be best to not use a badge for that kind of carousel and use the card content + button.

**Buttons/anchors**: This is fixed. It won't display empty box if you didn't set a text for the button.

**Carousel**: On mobile, I shrinked the card box and aligned it to the bottom of the image. I made a test and placed the card content box below the image but it gets to tall for most mobile screens. 

Thanks!
Simon

**Comment by Jessdwilson** [comment]
Thanks, Simon! 

We would prefer to go with the lighbox solution for the Collections page if you wouldn't mind sending us a time estimate when you get a chance.

**Comment by joauv** [comment]
A new module (Gallery) is now available. Important: when selecting images for a gallery, make sure the 'Title' and 'Description' attributes on the right are correctly filled (or empty). Those attributes will be used in the lightbox under the image.

The 'Load more' functionality has not been implemented yet.

![image](https://user-images.githubusercontent.com/7191186/29132922-c47e0282-7cff-11e7-89e2-441b0315740b.png)

**Comment by joauv** [comment]
On page load, the module will display 12 images and a 'Load More' button if there are >12 images. On click, 6 more images would appear, until there are no more images to display; the 'Load More' button would then disappear.

If you want to change the number of images displayed by default (12) or the increment (6), let us know!
