### ISSUE TITLE
Literary page

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/hbsc#43]
- [x] The images of the winners should be in b/w and hover to color on the Literary page. http://hbstowecenter.wpengine.com/literary-prize/

- [x] Can we have the option in WP to customize the last names to the Extra Condensed Slab typeface?

**Comment by Jessdwilson** [comment]
we will need to add color photos for participants (currently most are b&w), but agree that the images should hover to color

**Comment by spalepin** [comment]
Hello,

The wrong class was applied to the last name. It will now render as Extra Condensed automatically (same as an event).

Thanks
Simon
