### ISSUE TITLE
Student Stowe Prize entry form

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#45]
For the student stowe prize entry form, perhaps we could use Gravity forms to set this up? All submissions will need to be sent to a specific staff member, TBD. If you would prefer that we implement this, let me know. Thanks! 

<img width="611" alt="student stowe prize form" src="https://user-images.githubusercontent.com/1680051/28384228-efccca14-6c91-11e7-8ad3-9dcd84551c3e.png">

**Comment by spalepin** [comment]
Hello,

I was told that you wanted to use an external service to manage the form and tickets for the events. I thought that the form integration was done on you end.

We can help you integrating the form. Which service are you using to manage your forms/tickets?

Thanks!
Simon

**Comment by Jessdwilson** [comment]
Hi Simon,

The Student Stowe Prize entry form is different from the other ticket/event webforms that we'll handle in-house, Gravity Forms would probably be the best solution. I can have our developer implement when he works on the web forms if you prefer.

Thanks!

**Comment by spalepin** [comment]
Hi Jessica,

There's no problem if you're developer prefers to implement it while we take care of the other requests.

If we do it on our end, we will need more details about the entire registration process (on the administrative side).

Thanks
Simon
