### ISSUE TITLE
HBS Life page quote

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#46]
I don't see the option to edit this quote in WordPress for the Life page, it should be editable

<img width="1277" alt="screen shot 2017-07-19 at 4 08 13 pm" src="https://user-images.githubusercontent.com/1680051/28387347-afbcd15c-6c9c-11e7-86d9-ee2a00b4912f.png">

**Comment by spalepin** [comment]
Done!
