### ISSUE TITLE
Prize Participant paragraph text

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#48]
The bio text for Prize participants should extend the same width of the page as staff bios 
<img width="1273" alt="prize participant" src="https://user-images.githubusercontent.com/1680051/28393108-149ea7c4-6cb3-11e7-959e-11aafe549f7d.png">
<img width="1221" alt="staff" src="https://user-images.githubusercontent.com/1680051/28393115-1cc2f4fa-6cb3-11e7-8c6f-08e752841298.png">

**Comment by spalepin** [comment]
Done
