### ISSUE TITLE
Why Visit the Stowe Center design

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#5]
Can the Why Visit the Stowe Center page be similar to The Campus page? So "Be Inspired by the woman whose words changed the world" would appear in Rama beneath the page title, and the box links would be: The Tour, More Conversations at Stowe, Stowe House Preservation and If you can't visit in person
<img width="990" alt="screen shot 2017-06-28 at 5 56 05 pm" src="https://user-images.githubusercontent.com/1680051/27662261-15eadfe6-5c2b-11e7-9462-f529c056d485.png">

**Comment by spalepin** [comment]
Hello,

I updated the title of the page. I used the same styles as the campus page.
Thanks
Simon
![why_visit_stowe_center](https://user-images.githubusercontent.com/1513192/27694769-0fd57068-5cbb-11e7-959e-b7b3bd412805.jpg)
