### ISSUE TITLE
Student Stowe Prize entry module dates

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#51]
The first module on the [Student Stowe Prize](https://hbstowecenter.wpengine.com/student-stowe-prize/) should be editable, including the dates on the right-hand side using these parameters:

Date - Month, Day, Year 
Description - What the deadline is for
Status - Past, Present, Future

Elements appear in chronological order
Status indicates the color treatment of content

<img width="1286" alt="screen shot 2017-07-21 at 12 07 02 pm" src="https://user-images.githubusercontent.com/1680051/28472515-dec5c6d4-6e0e-11e7-98cc-1a93f6167fde.png">

**Comment by spalepin** [comment]
Done!

**Comment by Jessdwilson** [comment]
Great, thanks! 

The information to the left of the dates under **Prizes** appears to be hard-coded. I see another module below with the Prize info that is editable but this isn't the same as what appears in the first module, the first module with the dates needs to be editable

**Comment by spalepin** [comment]
Hello,

I modified the template to allow dynamic text content besides the nomination steps
I noticed that you created another student stowe prize page. However, I recommend editing this one below.
http://hbstowecenter.wpengine.com/stowe-prize/student-stowe-prize/

Please let me know if there's anything else.
Thanks
Simon
