### ISSUE TITLE
Salons at Stowe event Join and Share buttons

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#52]
- [x] On the Salons at Stowe event landing pages the "Join the Discussion" button should take the user to the online discussion section lower on the page
 
- [x] Clicking on the "Share" button should have a popup appear like in the attached mockup so users can share via social media or email

Thanks! 
[HBSC Web Design Refinement Share popup 20170721 RS.pdf](https://github.com/ObjectiveSubject/hbsc/files/1166336/HBSC.Web.Design.Refinement.Share.popup.20170721.RS.pdf)

**Comment by spalepin** [comment]
Hello,
I suggest a free sharing tool like AddThis. http://www.addthis.com/
Otherwise, If you prefer a custom sharing dialog like you have in the new designs, it can be done in about 2 to 2 1/2 hours.
Thanks
Simon

**Comment by Jessdwilson** [comment]
@joauv I don't see the share popup on the site after clearing my browser cache, it just redirects to the homepage. We had discussed with Simon implementing our design mockup

**Comment by joauv** [comment]
The site on wpengine hasn't been updated yet

**Comment by joauv** [comment]
Should be OK now
