### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/hbsc#53]
Hey. The navigation in the reduced state (Screenshot)...
![screen shot 2017-07-24 at 9 51 16 am](https://user-images.githubusercontent.com/12611145/28526533-ca78d2fe-7055-11e7-9828-dacc3385a6b5.png)

Opens to the full state (Screenshot)...
![screen shot 2017-07-24 at 9 51 22 am](https://user-images.githubusercontent.com/12611145/28526546-d4921c1e-7055-11e7-9688-7a3a2ca1f3e6.png)

There's a change in width. I think we should keep the width the same, most likely the wider instance.

**Comment by spalepin** [comment]
Hello,

The menu was the previously the same width as the wider submenu. When the menu is collapsed there's a big empty space at the right of the logo. 

Right now, there's a max-width when menu is collapsed to remove the empty space. 

Please let me know if you want to go ahead with the modification.

**No extra empty space (as it is right now) - Collapsed**
![image](https://user-images.githubusercontent.com/1513192/28675006-8b64311a-72b4-11e7-92b7-176c7cf39c38.png)


**Extra empty space - No max width - Collapsed**
![image](https://user-images.githubusercontent.com/1513192/28675039-a2fe5c9c-72b4-11e7-9e8a-0b5841179cb4.png)

**Comment by spalepin** [comment]
*If there is no max-width, the collapsed menu width will change when you add a new page with a long title.

**Comment by elliotarthur** [comment]
Hi Simon,

I think we should go with option 2 (**Extra empty space - No max width - Collapsed**). We'll also try to maintain the length of subtitles for the menu so we're not over shooting the length.

Thanks
