### ISSUE TITLE
Donate Page

### ISSUE THREAD

**Issue by ryanschoenherr** [ObjectiveSubject/hbsc#55]
Hey Simon,

Here's the donate page, you can also use the content provided within this mockup as its from their gather content. 

Best, 
Ryan
[Donate.pdf](https://github.com/ObjectiveSubject/hbsc/files/1183751/Donate.pdf)

**Comment by spalepin** [comment]
Thanks Rayan!

Have a great weekend
Simon

*Simon-Pierre Alepin*
Développeur web sénior
514 . 862 . 8844

<http://www.imagiamedia.ca>

**Comment by Jessdwilson** [comment]
Hi Ryan and Simon,

You do not need to design the donation page, this is a webform handled through Altru. Our in-house developer will implement following site launch.

Thanks!
