### ISSUE TITLE
People: Salons at Stowe

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#59]
For each person under staff & board there is a "Salons lead by..." section that includes a "Salons at Stowe" button, the button should link to the [Salons at Stowe landing page](https://hbstowecenter.wpengine.com/programs-learning/salons-at-stowe/)

 
<img width="1248" alt="screen shot 2017-08-02 at 1 01 18 pm" src="https://user-images.githubusercontent.com/1680051/28885241-29110168-7783-11e7-84ae-2d511b6865a3.png">

**Comment by spalepin** [comment]
Done!

**Comment by Jessdwilson** [comment]
@spalepin I just met with the client and they have a few requests which I'll be posting about. 

For the staff & board could the "Salons lead by..." section be an option? Many people won't be involved with the salons so the client may not want this section to appear. Perhaps with a check mark so the client can toggle it on or off?

**Comment by spalepin** [comment]
@Jessdwilson The section "Salons lead by" only appears if the member has lead at least 1 salon. Before the correction, it was showing an empty section even if the member didn't lead any salon. You may not need a toggle button anymore. Please let me know if it is necessary.

**Comment by Jessdwilson** [comment]
thanks! @spalepin that works
