### ISSUE TITLE
photos color on hover

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#6]
The photos and content should change color on hover, so the photo is black & white then when hovering over it changes to color (screenshots attached). This is mostly relevant for salons and the homepage. 
<img width="723" alt="static" src="https://user-images.githubusercontent.com/1680051/27662761-3e65d5fa-5c2d-11e7-9fa5-3adc3151c0a3.png">
<img width="698" alt="hover" src="https://user-images.githubusercontent.com/1680051/27662769-458f5aea-5c2d-11e7-9402-333d2f4610eb.png">

**Comment by spalepin** [comment]
Hello,

This is done!

Thanks
Simon

**Comment by Jessdwilson** [comment]
Hi Simon, on the Salons at Stowe page, can the Past Salons photos also appear in black and white and change to color on hover? 
<img width="1240" alt="screen shot 2017-07-14 at 4 33 35 pm" src="https://user-images.githubusercontent.com/1680051/28229988-1d8c75cc-68b3-11e7-9206-9784be726f80.png">

**Comment by spalepin** [comment]
Done!
