### ISSUE TITLE
content entry: template and modules types

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#60]
Hi @spalepin you had mentioned sending a breakdown on what the different templates and modules are used for, would you mind providing this? For templates, it seems that most pages use default correct?

Here is what we have in WordPress - 

**Templates:**
Default
Basic Anchor template
Calendar (self-explanatory)
Events Post list 
Life
Stowe Center Impact & Issues 

**Modules**
Entry
Carousel
Media Collection
Hero
List 
Video (self-explanatory)
Participant (self-explanatory, for Stowe Prize winners)

**Comment by spalepin** [comment]
@Jessdwilson You're right, most pages use the default template which has a preface (intro text) by default.

Please let me know if you need more details!

Templates:

**Default**
- Preface intro section
- Can add modules

**Basic Anchor template**
- Not used, same as default page template

**Calendar (self-explanatory)**

**Events Post list**
- List event posts with sorting
https://hbstowecenter.wpengine.com/events-list/

**Life Stowe Center Impact & Issues**
- Almost the same as the default template
- Layout customized for this page only


Modules

**Basic**
- Can add an hero image that appears above the content
- Can display an anchor button in the preface (links to the module section)

**Entry**
- Can add an hero image that appears above the content
- Text section that takes 2/3 of page width
- Optional side bar content or button
- Can display an anchor button in the preface (links to the module section)

**Carousel**
- Carousel slides with navigation

**Media Collection**
- Carousel slides with navigation, different layout than the carousel module

**Hero**
- Hero image as a background
- Card with text & button that appears on top of the background image
- Card color is customizable

**List(not used anymore - tbc)
Video (self-explanatory)
Participant (self-explanatory, for Stowe Prize winners)**
