### ISSUE TITLE
User Comments 

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#62]
When users add comments to the site could a single person on the client's team receive notifications that a new comment has posted?

**Comment by spalepin** [comment]
@Jessdwilson I'm currently using my own disqus account for the comments. I can setup the comments with you account. I believe there is an option in disqus to notify the moderator by email. I need the email/username and password to do the setup.
Thanks

**Comment by Jessdwilson** [comment]
@spalepin just to confirm, HBSC needs to setup their own Disqus account and we should then send you their Disqus username and password, right?

**Comment by joauv** [comment]
Yes exactly, and that way they can decide what email get notified, etc.

**Comment by Jessdwilson** [comment]
the client sent over their Disqus credentials:

username: HarrietBeecherStoweCenter
password: VictorianWalls
