### ISSUE TITLE
People: Staff & Board

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#63]
- [x] The client has requested that staff and board have separate pages

- [x] Board members should not have separate landing pages, their names and titles should only appear on the page but will not be clickable 

- [x] The client has requested that the font size for staff and board be reduced by a couple points, they feel it's too large 

- [x] They would like to add a new role, "Salon Host" for individuals who are not staff members but may host salons. I tried adding this role but found that they appear on the staff & board page, can this be fixed so they only show up as an option under Discussion Leaders for Events?

**Comment by joauv** [comment]
'Staff & Board' menu-item under 'About' has been replaced by 'Staff' and 'Board' (separate items), each linking to its own page. Board members' name doesn't link to individual profile page anymore. People put _only_ in the 'Salon Host' category will not show up on either of those two pages.
