### ISSUE TITLE
Stowe Prize winner 

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#64]
- [x] I noticed on the Literary Prize winner landing pages the breadcrumb is incorrect, it should be Literary Prize not Student Stowe Prize 

- [x] can the Participant headline be removed on all prize winner landing pages?

- [x] For Literary Prize winners only can "topic" be removed so it doesn't appear on the front-end? Topic should only appear for Student Stowe Prize winners 

<img width="1138" alt="screen shot 2017-08-03 at 5 21 34 pm" src="https://user-images.githubusercontent.com/1680051/28944736-a2fb217c-7871-11e7-8727-8b8722d28f49.png">

**Comment by kpettinga** [comment]
@Jessdwilson this should be all set. In order to make the breadcrumbs work as they should, within the system that Webit setup, I needed to separate the literary and student participants into two post types. So you'll see that in the backend now.
