### ISSUE TITLE
Salons at Stowe: Upcoming and Past Salons

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#67]
- [x] On the Salons at Stowe page the events under Upcoming Salons are all past salons, and the events under Past Salons are all upcoming 

- [x] On the Salons at Stowe page, since it may not be relevant for some time could we disable the items beneath Past Salons: "Recent", "Most Viewed" and "Most Discussed"
So just Past Salons appear in this section 

<img width="1197" alt="screen shot 2017-08-15 at 1 33 05 pm" src="https://user-images.githubusercontent.com/1680051/29327875-97775de2-81be-11e7-8a3e-0bda7724b9cd.png">

**Comment by spalepin** [comment]
@Jessdwilson I can remove the sort buttons for the past salons. I had a configuration issue with disqus comments count, the most discussed filter was not accurate(staging was). Please let me know how the posts should be sorted if we remove the filters.
Thanks

**Comment by Jessdwilson** [comment]
hi @spalepin for the Past Salons section, if we remove the 3 filters the salon events should appear in order of the most recent past events to the distant past events as you scroll down
