### ISSUE TITLE
Navigation: Arrow visible at initial stage

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/hbsc#7]
The navigation menu [on Chrome] displays the arrow next to stowe prize. This should be hidden at the initial view. Screen shot below

![screen shot 2017-06-30 at 12 20 10 pm](https://user-images.githubusercontent.com/12611145/27744680-7b0d9846-5d8e-11e7-8423-2fe592b58024.png)

**Comment by spalepin** [comment]
This is done!
Thanks
