### ISSUE TITLE
Board page: adding a link

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#71]
I know that we now have separate pages for staff and board but when looking under pages the Staff & Board page still appears. There will be a password-protected page that we need to add to the Board landing page for Board members only to access. We have the password protected Board page set up, but will need the ability to add this to the Board landing page; could we add a sidebar link to the Board landing page so we can add the password protected page as a link?

<img width="849" alt="screen shot 2017-08-21 at 3 03 52 pm" src="https://user-images.githubusercontent.com/1680051/29534136-de9098ba-8682-11e7-8a1d-8946d67ba262.png">

**Comment by joauv** [comment]
I put the old Staff & Board page to the trash. Not sure I fully understand this... I can see the new password-protected 'Board' page, however there will probably need to be a custom template made for this, or else all the modules added to the page will be visible at all times, password or not. The native WP behavior with password protected pages is to protect only the content (what is entered in the WYSIWYG editor), and I reckon this is not the desired effect here (unless there are zero modules on that page/modules should be visible anyway?).

Also, I'm not sure on what page that sidebar/link to the page should go?

**Comment by Jessdwilson** [comment]
Thanks @joauv I didn't realize that the modules the client adds will be visible, I will let them know to only add private documents to the WYSIWYG editor. They will mostly be saving PDF files here. 

So the password protected Board page needs to be added as a link on the [Board landing page](https://hbstowecenter.wpengine.com/roles/board/). I was thinking it would make sense in the sidebar and say "Board of Trustees Login" perhaps in a red button?

**Comment by joauv** [comment]
Unfortunately, there is no sidebar in that layout. The content is full width in order to be centered in the page. Best I can do at the moment is this:
![image](https://user-images.githubusercontent.com/7191186/29673674-f12d0da4-88bd-11e7-8b6c-2d454f90a376.png)
Let me know if that's OK. Also, that button would lead to the new 'Board' protected page? (just to make sure)

**Comment by Jessdwilson** [comment]
Hi @joauv the location for the link is fine, thanks. And yes the link should go to the [password protected board page](https://hbstowecenter.wpengine.com/board/) . Thanks!
