### ISSUE TITLE
Salons at Stowe: responsive display

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#74]
I noticed on an event landing page the "Upcoming Salon" event is responding strangely for desktop but appears accurate in tablet and mobile view, screenshots attached 

<img width="1150" alt="desktop" src="https://user-images.githubusercontent.com/1680051/29780046-67d05f20-8be2-11e7-8335-23ce2724e5f3.png">

<img width="387" alt="mobile" src="https://user-images.githubusercontent.com/1680051/29780063-751c661a-8be2-11e7-9ed2-ee5265b91945.png">

<img width="612" alt="tablet" src="https://user-images.githubusercontent.com/1680051/29780054-6e273a4c-8be2-11e7-8aec-817bffea3607.png">

**Comment by Jessdwilson** [comment]
this particular event text is still breaking strangely on desktop on the Salons at Stowe page and on event landing pages, is it possible to fix?

<img width="573" alt="screen shot 2017-08-30 at 10 38 10 am" src="https://user-images.githubusercontent.com/1680051/29878277-1b665736-8d70-11e7-891c-b6b734ccc683.png">
<img width="494" alt="screen shot 2017-08-30 at 10 43 28 am" src="https://user-images.githubusercontent.com/1680051/29878293-27d23a4e-8d70-11e7-86dd-0a64065bf7d0.png">

**Comment by kpettinga** [comment]
@Jessdwilson this is happening because the text is too large and "islamophobia" is a big word for such a small space. I decreased the font size a bit to allow for longer words.
