### ISSUE TITLE
Mission Statement Text Links color

### ISSUE THREAD

**Issue by ryanschoenherr** [ObjectiveSubject/hbsc#75]
The mission statement on the homepage should have in text links that link to pages throughout the website. These links are italic and turn red on hover. 

We preserve and interpret _Stowe’s Hartford home_ and the center’s _historic collections_, promote vibrant discussion of her _life and work_, and inspire commitment to _social justice and positive change._

 _Stowe’s Hartford home_  links to https://hbstowecenter.wpengine.com/visit/campus/

 _historic collections_ links to https://hbstowecenter.wpengine.com/programs-learning/collections/

 _life and work_, links to https://hbstowecenter.wpengine.com/harriet-beecher-stowe/harriet-beecher-stowe-life/

 _social justice and positive change._ links to https://hbstowecenter.wpengine.com/programs-learning/salons-at-stowe/

**Comment by Jessdwilson** [comment]
Would it be possible for just the mission statement in the header of the homepage to have a different link color than other links on the site? We were hoping that the italicized links could remain black and turn red on hover

<img width="1212" alt="screen shot 2017-08-29 at 1 05 23 pm" src="https://user-images.githubusercontent.com/1680051/29833848-c0f363f8-8cba-11e7-9f98-21f145224161.png">
