### ISSUE TITLE
Hours & Admission page

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#77]
- [x] There doesn't appear to be the option to edit the text above the Hours on the Hours & Admissions page, could this be an option for the client to edit?
<img width="1132" alt="hours text" src="https://user-images.githubusercontent.com/1680051/29842126-e5b3fee4-8cd5-11e7-90c3-3273b08bda68.png">

- [x] the client asked if it's possible to refine the alignment for the directions, I took a look in wordpress and struggled to get the text precisely aligned. If it would help with the alignment, perhaps this info could be hard coded since it's not likely to ever change? 
<img width="768" alt="directions alignment" src="https://user-images.githubusercontent.com/1680051/29842137-ef2c4dd2-8cd5-11e7-874f-4d5c86e83f67.png">

**Comment by kpettinga** [comment]
@Jessdwilson 

> text above the Hours

I've added a new field to the General Settings tab called "Hours Description". Text can be edited there.

> alignment for the directions

Just needed a CSS tweak. All set.
