### ISSUE TITLE
Donate Now url link

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#80]
I tried adding the donation link to the Donate Now button link on [this page](https://hbstowecenter.wpengine.com/support/donate/) in WordPress but it won't save and seems to only allow links to pages within the site. Here is the webform donation link: https://64527.blackbaudhosting.com/64527/Operating-Total

<img width="900" alt="screen shot 2017-08-30 at 11 29 49 am" src="https://user-images.githubusercontent.com/1680051/29881215-fe70e346-8d77-11e7-9ae2-6dc965e49a94.png">

**Comment by kpettinga** [comment]
@Jessdwilson all set here. 
I added support for an external link to be added as well. Updated the donate page with the link to the form as well.
