### ISSUE TITLE
Event Registration custom field

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#81]
You will see the "Register" button on the top right of event landing pages, each event should have the option to include a registration link to connect an Altru webform 

<img width="1093" alt="screen shot 2017-08-30 at 11 44 28 am" src="https://user-images.githubusercontent.com/1680051/29881497-b5facf18-8d78-11e7-9aa9-500f537fe2ca.png">

**Comment by kpettinga** [comment]
All set, field added.
