### ISSUE TITLE
button link color shortcode

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#82]
There is a button shortcode so the client can add button links anywhere on the site, they asked for a color shortcode option so that some buttons could be red with white text similar to the attached from the Join page, currently, buttons created using the shortcode are white with black text 

<img width="315" alt="screen shot 2017-08-30 at 11 54 38 am" src="https://user-images.githubusercontent.com/1680051/29882159-355d4ba4-8d7a-11e7-9e36-e5bceff24d8a.png">

**Comment by kpettinga** [comment]
@Jessdwilson this already exists. Just use the `color="red"` option.

Example:
```
[button link="http://google.com" color="red"]Some Text[/button]
```
