### ISSUE TITLE
Preview Changes in WordPress

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#83]
for some reason clicking the Preview Changes button in WordPress isn't working, if we make any changes to a page and click Preview Changes it doesn't show the changes unless we click Update and view the page

**Comment by kpettinga** [comment]
@Jessdwilson I just tried this out and it seems to be working.. Can you confirm?

If it's still broken, let me know what page and what field(s) you're trying to edit.
