### ISSUE TITLE
mobile: text length

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#89]
[Salons at Stowe homepage text cutoff.zip](https://github.com/ObjectiveSubject/hbsc/files/1270279/Salons.at.Stowe.homepage.text.cutoff.zip)
in mobile there are many instances where the text breaks within words, is it possible for the font size to reduce further in mobile so words remain on single lines? 

![homepage mobile](https://user-images.githubusercontent.com/1680051/29971008-bbacb6e2-8ef4-11e7-9737-cd3adca1db16.PNG)

**Comment by Jessdwilson** [comment]
I'm still seeing issues where the text breaks, is it possible to further reduce the font size in mobile?

![img_5786](https://user-images.githubusercontent.com/1680051/30835091-5ad8e550-a224-11e7-92aa-183f1ce992cc.PNG)
![img_5787](https://user-images.githubusercontent.com/1680051/30835093-5c6435b4-a224-11e7-820d-8bbb52667548.PNG)
![img_5788](https://user-images.githubusercontent.com/1680051/30835095-5d94e078-a224-11e7-8eb5-bc3a2018ff53.PNG)

**Comment by joauv** [comment]
Sure. Also, this issue is mainly caused by the restrictive nature of the design itself (see 'Salons' cards, space lost on the left, and again on the left of the block itself...) Do you think it would be possible for me to adapt it on smaller screens so I can maximize the space available for the text (instead of constantly just making the text smaller and smaller)?

**Comment by Jessdwilson** [comment]
I'm not entirely sure what you mean. We could adjust the photos in mobile so they are full bleed and adjust the cards so they are wider but still keep a margin then center the content on the screen so it reads better in mobile, is that kind of what you're suggesting?

**Comment by Jessdwilson** [comment]
@joauv our designer created some quick mockups to give you an idea of what we're thinking for displaying events in mobile

[iPhone 7 past salons.pdf](https://github.com/ObjectiveSubject/hbsc/files/1333745/iPhone.7.past.salons.pdf)


[iPhone 7 upcoming salons.pdf](https://github.com/ObjectiveSubject/hbsc/files/1333744/iPhone.7.upcoming.salons.pdf)

**Comment by Jessdwilson** [comment]
thanks! @joauv the events in mobile do look a lot better, we were wondering if for Upcoming Salons could the photo be full bleed to avoid instances where a comma goes to the next line? For Past Salons, could the event date box be widened to avoid the date falling on 2 or 3 lines? 

![img_5792](https://user-images.githubusercontent.com/1680051/30931526-edd44f60-a392-11e7-8e37-b8d4171f6870.PNG)
![img_5791](https://user-images.githubusercontent.com/1680051/30931531-f25f5390-a392-11e7-9b45-e8793b4cfa95.PNG)
