### ISSUE TITLE
Calendar: Rollover on events

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/hbsc#9]
- [x] Can the header have the same reaction time as the smaller copy when the user hovers over the box? The event title has a slower transformation.

- [x] Remove the tan outline on hover or make it red like the box fill.

- [x] I don't think we need the event title to have it's own rollover instance [black and underline]. Can remove those?

**Comment by spalepin** [comment]
Hello,

This is done!
Thanks
