### ISSUE TITLE
Newsletter signup field

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#94]
the newsletter signup field should be connected to their Constant Contact account (login credentials are forthcoming)

**Comment by Jessdwilson** [comment]
Constant Contact login credentials:
username: harrietbeecherstowe
pw: abolition

**Comment by joauv** [comment]
They need to create a list (or pick an existing one) to collect the emails. I can create one myself, but I just want to make sure they do not intend to have those emails in an existing list before doing so.

http://techblog.constantcontact.com/api/how-to/how-to-modify-embed-code/
^Link above is just for future reference

**Comment by Jessdwilson** [comment]
I confirmed with the client, they would like email signups to be connected to the list called “Monthly E-News”

Thanks!

**Comment by joauv** [comment]
The sign-up form works now, emails provided will be added to the Monthly E-News list. However, Constant Contact strongly suggest to have this text under (or somewhere around) the form:

_By submitting this form, you are granting: Harriet Beecher Stowe Center, 77 Forest Street, Hartford, Connecticut, 06105, United States, http://www.harrietbeecherstowe.org permission to email you. You may unsubscribe via the link found at the bottom of every email.  (See our Email Privacy Policy for details.) Emails are serviced by Constant Contact._

Here's what they say about it on their site:

**Unsubscribe Information in Form Footer**
It is highly recommended that you include text in the form footer that says “You may unsubscribe via the link found at the bottom of every email.” By removing or modifying this text, you could run afoul of both US and Canadian anti-spam legislation.

Let me know if what I've done is OK with you/your designer, or if you want to edit the text, etc.

**Comment by Jessdwilson** [comment]
thanks! I think what you've added looks fine.

**Comment by Jessdwilson** [comment]
question from the client: I believe Constant Contact requires a first and last name to go with the email addresses. I believe this is to prevent spamming. I think the E-News sign up link on our old website had an intermediate step where the user provides this information. Could this be added to the newsletter signup on the site?

**Comment by joauv** [comment]
Constant Contact doesn't require first and last names when signing up (only the email is mandatory), and providing those won't prevent spamming in any way. However, if the client wants to have first/last name fields added to the sign up form, it can be done but again, won't prevent spamming.

**Comment by Jessdwilson** [comment]
ok, thanks. Yes, if you could add the requirement for first and last names to be entered that would be great, I think this would be beneficial as well for their database 

Thanks!
